# Generated by Django 4.1.7 on 2023-03-16 17:48

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('session_id', models.CharField(max_length=320, primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('date_last_used', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('is_waiting', models.BooleanField(default=False)),
                ('year_before', models.IntegerField(null=True)),
                ('year_after', models.IntegerField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('rating', models.IntegerField(null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('year_relevance', models.IntegerField(null=True)),
                ('year_relevace_before', models.IntegerField(null=True)),
                ('year_relevance_after', models.IntegerField(null=True)),
                ('duration_relevance', models.IntegerField(null=True)),
                ('country_relevance', models.IntegerField(null=True)),
                ('author_relevance', models.IntegerField(null=True)),
                ('genres_relevance', models.IntegerField(null=True)),
                ('actors', models.ManyToManyField(null=True, to='main.actor')),
                ('genres', models.ManyToManyField(null=True, to='main.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2030)])),
                ('duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('country', models.CharField(max_length=255)),
                ('synopsis', models.TextField()),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('cover_url', models.URLField(max_length=255)),
                ('authors', models.ManyToManyField(to='main.actor')),
                ('genres', models.ManyToManyField(to='main.genre')),
            ],
        ),
    ]
