# Generated by Django 4.1.7 on 2023-03-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='authors',
            new_name='actors',
        ),
    ]
