# Generated by Django 4.1.4 on 2023-03-16 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_movie_duration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersession",
            old_name="author_relevance",
            new_name="actors_relevance",
        ),
        migrations.RenameField(
            model_name="usersession",
            old_name="year_relevace_before",
            new_name="rating_relevance",
        ),
        migrations.RemoveField(
            model_name="usersession",
            name="year_relevance_after",
        ),
    ]
